openapi: 3.0.0
info:
  title: Task Management API
  description: API for managing user tasks in the Todo application
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.todoapp.com
    description: Production server

paths:
  /api/{user_id}/tasks:
    get:
      summary: Get all tasks for a user
      description: Retrieve all tasks belonging to the specified user
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user whose tasks to retrieve
          schema:
            type: string
        - name: status
          in: query
          required: false
          description: Filter tasks by completion status (all, pending, completed)
          schema:
            type: string
            enum: [all, pending, completed]
            default: all
        - name: sort
          in: query
          required: false
          description: Sort tasks by criteria (created, title)
          schema:
            type: string
            enum: [created, title]
            default: created
      responses:
        '200':
          description: Successful response with user's tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '404':
          description: User not found
      security:
        - bearerAuth: []

    post:
      summary: Create a new task
      description: Create a new task for the specified user
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user creating the task
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskRequest'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Bad request - Invalid input data
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '404':
          description: User not found
      security:
        - bearerAuth: []

  /api/{user_id}/tasks/{task_id}:
    get:
      summary: Get a specific task
      description: Retrieve a specific task by ID for the specified user
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user
          schema:
            type: string
        - name: task_id
          in: path
          required: true
          description: ID of the task to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Successful response with the task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '404':
          description: Task not found for the user
      security:
        - bearerAuth: []

    put:
      summary: Update a task
      description: Update an existing task for the specified user
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user
          schema:
            type: string
        - name: task_id
          in: path
          required: true
          description: ID of the task to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTaskRequest'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Bad request - Invalid input data
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '404':
          description: Task not found for the user
      security:
        - bearerAuth: []

    delete:
      summary: Delete a task
      description: Delete a specific task for the specified user
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user
          schema:
            type: string
        - name: task_id
          in: path
          required: true
          description: ID of the task to delete
          schema:
            type: string
      responses:
        '204':
          description: Task deleted successfully
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '404':
          description: Task not found for the user
      security:
        - bearerAuth: []

    patch:
      summary: Toggle task completion status
      description: Toggle the completion status of a specific task for the specified user
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user
          schema:
            type: string
        - name: task_id
          in: path
          required: true
          description: ID of the task to toggle
          schema:
            type: string
      responses:
        '200':
          description: Task completion status toggled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '404':
          description: Task not found for the user
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Task:
      type: object
      required:
        - id
        - userId
        - title
        - completed
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
          description: Unique identifier for the task
        userId:
          type: string
          description: ID of the user who owns this task
        title:
          type: string
          description: Task title (1-200 characters)
          minLength: 1
          maxLength: 200
        description:
          type: string
          description: Detailed task description (optional, max 1000 characters)
          maxLength: 1000
        completed:
          type: boolean
          description: Whether the task is marked as complete
          default: false
        createdAt:
          type: string
          format: date-time
          description: Timestamp when task was created
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when task was last updated

    CreateTaskRequest:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          description: Task title (1-200 characters)
          minLength: 1
          maxLength: 200
        description:
          type: string
          description: Detailed task description (optional, max 1000 characters)
          maxLength: 1000

    UpdateTaskRequest:
      type: object
      properties:
        title:
          type: string
          description: Task title (1-200 characters)
          minLength: 1
          maxLength: 200
        description:
          type: string
          description: Detailed task description (optional, max 1000 characters)
          maxLength: 1000
        completed:
          type: boolean
          description: Whether the task is marked as complete